SIFT: obvious::TsdGrid Class Reference
obvious::TsdGrid Class Reference
Grid on the basis of true signed distance functions.
#include <TsdGrid.h>
Public Member Functions
TsdGrid (const obfloat cellSize, const EnumTsdGridLayout layoutPartition, const EnumTsdGridLayout layoutGrid)
Standard constructor Allocates and initializes space and matrices.
TsdGrid (const std::string &data, const EnumTsdGridLoadSource source=FILE_SOURCE)
Constructor Loads the grid data out of a given file.
virtual ~TsdGrid ()
Destructor.
void reset ()
Reset TSD grid (delete and re-instantiate cells)
obfloat & operator() (unsigned int y, unsigned int x) const
Access truncated signed distance at specific cell.
unsigned int getCellsX () const
Get number of cells in x-dimension.
unsigned int getCellsY () const
Get number of cells in y-dimension.
obfloat getCellSize () const
Get size of cell in meters.
obfloat getMinX () const
Get minimum for x-coordinate.
obfloat getMaxX () const
Get maximum for x-coordinate.
void getCentroid (double centroid[2])
Get centroid of grid.
obfloat getMinY () const
Get minimum for y-coordinate.
obfloat getMaxY () const
Get maximum for y-coordinate.
unsigned int getPartitionSize () const
Get number of cells along edge.
void setMaxTruncation (const double val)
Set maximum truncation radius.
double getMaxTruncation () const
Get maximum truncation radius.
void push (SensorPolar2D *sensor)
Push current measurement from sensor.
void grid2ColorImage (unsigned char *image, unsigned int width, unsigned int height)
Create color image from tsdf grid.
bool interpolateNormal (const obfloat coord[2], obfloat normal[2])
Calculates normal of plain element hit by a ray caster.
EnumTsdGridInterpolate interpolateBilinear (obfloat coord[2], obfloat *tsd)
interpolate bilinear
bool coord2Cell (obfloat coord[2], int *p, int *x, int *y, obfloat *dx, obfloat *dy)
Convert arbitrary coordinate to grid coordinates.
TsdGridPartition *** getPartitions () const
Get pointer to internal partition space.
bool isInsideGrid (Sensor *sensor)
Determine whether sensor is in grid.
bool storeGrid (const std::string &path)
Method to write the content of the grid into a given file.
bool freeFootprint (const obfloat centerCoords[2], const obfloat width, const obfloat height)
Method to set the grid in a certain area as empty.
Detailed Description
Grid on the basis of true signed distance functions.
Author
Stefan May, Philipp Koch
Constructor & Destructor Documentation
obvious::TsdGrid::TsdGrid (const obfloat cellSize, const EnumTsdGridLayout layoutPartition, const EnumTsdGridLayout layoutGrid)
Standard constructor Allocates and initializes space and matrices.
Parameters
[in] cellSize Size of cell in meters
[in] layoutPartition Partition layout, i.e., cells in partition
[in] layoutGrid Grid layout, i.e., partitions in grid
obvious::TsdGrid::TsdGrid (const std::string & data, const EnumTsdGridLoadSource source = FILE_SOURCE)
Constructor Loads the grid data out of a given file.
File has to be correct it is not being checked.
Parameters
[in] path path to the data file
Member Function Documentation
obfloat& obvious::TsdGrid::operator() (unsigned int y, unsigned int x) const inline
Access truncated signed distance at specific cell.
This method does not check validity of indices. The specific cell might not be instantiated.
Parameters
y y coordinate
x x coordinate
Returns
truncated signed distance
unsigned int obvious::TsdGrid::getCellsX () const inline
Get number of cells in x-dimension.
Returns
number of cells
unsigned int obvious::TsdGrid::getCellsY () const inline
Get number of cells in y-dimension.
Returns
number of cells
obfloat obvious::TsdGrid::getCellSize () const inline
Get size of cell in meters.
Returns
size
obfloat obvious::TsdGrid::getMinX () const inline
Get minimum for x-coordinate.
Returns
x-coordinate
obfloat obvious::TsdGrid::getMaxX () const inline
Get maximum for x-coordinate.
Returns
x-coordinate
References getCentroid().
void obvious::TsdGrid::getCentroid (double centroid[2])
Get centroid of grid.
Parameters
[out] centroid centroid coordinates
Referenced by getMaxX().
obfloat obvious::TsdGrid::getMinY () const inline
Get minimum for y-coordinate.
Returns
y-coordinate
obfloat obvious::TsdGrid::getMaxY () const inline
Get maximum for y-coordinate.
Returns
y-coordinate
unsigned int obvious::TsdGrid::getPartitionSize () const inline
Get number of cells along edge.
Returns
number of cells
References obvious::TsdGridPartition::getWidth(), and setMaxTruncation().
void obvious::TsdGrid::setMaxTruncation (const double val)
Set maximum truncation radius.
Parameters
[in] val truncation radius
Referenced by getPartitionSize().
double obvious::TsdGrid::getMaxTruncation () const inline
Get maximum truncation radius.
Returns
truncation radius
References coord2Cell(), grid2ColorImage(), interpolateBilinear(), interpolateNormal(), and push().
void obvious::TsdGrid::push (SensorPolar2D * sensor)
Push current measurement from sensor.
Parameters
[in] virtual 2D measurement unit
Referenced by getMaxTruncation().
void obvious::TsdGrid::grid2ColorImage (unsigned char * image, unsigned int width, unsigned int height)
Create color image from tsdf grid.
Parameters
[out] color image (3-channel)
Referenced by getMaxTruncation().
bool obvious::TsdGrid::interpolateNormal (const obfloat coord[2], obfloat normal[2])
Calculates normal of plain element hit by a ray caster.
Parameters
[out] coordinates
[out] normal vector
Referenced by getMaxTruncation().
EnumTsdGridInterpolate obvious::TsdGrid::interpolateBilinear (obfloat coord[2], obfloat * tsd) inline
interpolate bilinear
Parameters
coordinates pointer to coordinates of intersection
[out] tsdf interpolated TSD value
References coord2Cell(), and obvious::TsdGridPartition::interpolateBilinear().
Referenced by getMaxTruncation().
bool obvious::TsdGrid::coord2Cell (obfloat coord[2], int * p, int * x, int * y, obfloat * dx, obfloat * dy) inline
Convert arbitrary coordinate to grid coordinates.
Parameters
[in] coord 2D query coordinates
[out] x x-index
[out] y y-index
[out] dx x-coordinate of cell-center in metric space
[out] dy y-coordinate of cell-center in metric space
Referenced by getMaxTruncation(), and interpolateBilinear().
TsdGridPartition*** obvious::TsdGrid::getPartitions () const inline
Get pointer to internal partition space.
Returns
pointer to 3D partition space
References freeFootprint(), isInsideGrid(), and storeGrid().
bool obvious::TsdGrid::isInsideGrid (Sensor * sensor) inline
Determine whether sensor is in grid.
Parameters
sensor
References obvious::Sensor::getPosition().
Referenced by getPartitions().
bool obvious::TsdGrid::storeGrid (const std::string & path)
Method to write the content of the grid into a given file.
Parameters
path Path where data file is created
Returns
True in case of success
Referenced by getPartitions().
bool obvious::TsdGrid::freeFootprint (const obfloat centerCoords[2], const obfloat width, const obfloat height)
Method to set the grid in a certain area as empty.
Parameters
centerCoords footprint center
width width of footprint
height height of footprint
Returns
true in case of success (valid coordinates)
Referenced by getPartitions().
The documentation for this class was generated from the following file:
TsdGrid.h