SIFT: obvious::AnnPairAssignment Class Reference
obvious::AnnPairAssignment Class Reference
Encapsulates neighbor searching with approximate nearest neighbor algorithm (ANN)
#include <AnnPairAssignment.h>
Public Member Functions
AnnPairAssignment ()
Default constructor.
AnnPairAssignment (int dimension)
Standard constructor.
~AnnPairAssignment ()
Destructor.
void setMaxVisitPoints (unsigned int visitPoints)
Set maximum number of point to be visited until interruption.
void setModel (double **model, int size)
Set model as matching base.
void determinePairs (double **scene, bool *msk, int size)
Determine point pairs.
ANNkd_tree * getTree ()
Get the constructed kd-tree.
Public Member Functions inherited from obvious::PairAssignment
PairAssignment ()
Default constructor.
PairAssignment (int dimension)
Standard constructor.
virtual ~PairAssignment ()
Standard destructor.
virtual vector< StrCartesianIndexPair > * getPairs ()
Access internal container of assigned pair indices.
virtual vector< double > * getDistancesSqr ()
Access squared distances between index pairs.
virtual vector< unsigned int > * getNonPairs ()
Access internal container of non-assigned point indices.
virtual int getDimension ()
Dimension of space.
void determinePairs (double **scene, int size)
Determine point pairs (generic implementation)
void reset ()
clear vector of Cartesian point pairs and reset post assignment filters
Additional Inherited Members
Protected Member Functions inherited from obvious::PairAssignment
virtual void addPair (unsigned int indexModel, unsigned int indexScene, double distanceSqr)
add assigned point to internal vector
virtual void addNonPair (unsigned int indexScene)
add non-assigned point to internal vector
Protected Attributes inherited from obvious::PairAssignment
int _dimension
Dimension of space.
double ** _model
the 2D or 3D model
int _sizeModel
model size / number of points
Detailed Description
Encapsulates neighbor searching with approximate nearest neighbor algorithm (ANN)
Author
Stefan May
Member Function Documentation
void obvious::AnnPairAssignment::setMaxVisitPoints (unsigned int visitPoints)
Set maximum number of point to be visited until interruption.
This option enhances the performance, but can raise non-optimal matches.
Parameters
visitPoints number of points to be visited
Referenced by AnnPairAssignment().
void obvious::AnnPairAssignment::setModel (double ** model, int size) virtual
Set model as matching base.
Parameters
model array of xy values
size number of points
Implements obvious::PairAssignment.
Referenced by AnnPairAssignment().
void obvious::AnnPairAssignment::determinePairs (double ** scene, bool * msk, int size) virtual
Determine point pairs.
Parameters
scene scene to be compared
msk validity mask
size nr of points in scene
Implements obvious::PairAssignment.
Referenced by AnnPairAssignment().
ANNkd_tree* obvious::AnnPairAssignment::getTree ()
Get the constructed kd-tree.
Returns
Pointer to the internally used kd-tree-structure constructed by libANN
Referenced by AnnPairAssignment().
The documentation for this class was generated from the following file:
AnnPairAssignment.h