SIFT: obvious::TsdSpace Class Reference
obvious::TsdSpace Class Reference
Space representing a true signed distance function.
#include <TsdSpace.h>
Public Member Functions
TsdSpace (const double voxelSize, const EnumTsdSpaceLayout layoutPartition, const EnumTsdSpaceLayout layoutSpace)
Standard constructor.
virtual ~TsdSpace ()
Destructor.
void reset ()
Reset space to initial state.
unsigned int getXDimension () const
Get number of voxels in x-direction.
unsigned int getYDimension () const
Get number of voxels in y-direction.
unsigned int getZDimension () const
Get number of voxels in z-direction.
int getPartitionsInX () const
Get number of partitions in x-direction.
int getPartitionsInY () const
Get number of partitions in y-direction.
int getPartitionsInZ () const
Get number of partitions in z-direction.
obfloat getVoxelSize () const
Get edge length of voxels.
unsigned int getPartitionSize ()
Get number of cells along edge.
obfloat getMinX () const
Get minimum for x-coordinate.
obfloat getMaxX () const
Get maximum for x-coordinate.
obfloat getMinY () const
Get minimum for y-coordinate.
obfloat getMaxY () const
Get maximum for y-coordinate.
obfloat getMinZ () const
Get minimum for z-coordinate.
obfloat getMaxZ () const
Get maximum for z-coordinate.
void getCentroid (obfloat centroid[3])
Get centroid of space.
void setMaxTruncation (const obfloat val)
Set maximum truncation radius Function to set the max truncation.
double getMaxTruncation () const
Get maximum truncation radius.
TsdSpacePartition **** getPartitions () const
Get pointer to internal partition space.
bool isPartitionInitialized (obfloat coord[3])
Check, if partition belonging to coordinate is initialized.
bool isInsideSpace (Sensor *sensor)
Determine whether sensor is inside space.
void push (Sensor *sensor)
Push sensor data to space.
void pushTree (Sensor *sensor)
Push sensor data to space using octree insertion.
EnumTsdSpaceInterpolate interpolateTrilinear (obfloat coord[3], obfloat *tsd)
interpolate_trilineary Method to interpolate TSDF trilineary
EnumTsdSpaceInterpolate interpolateTrilinearRGB (obfloat coord[3], unsigned char rgb[3])
interpolate_trilineary Method to interpolate RGB data trilineary
bool interpolateNormal (const obfloat *coord, obfloat *normal)
Calculates normal of crossed surface.
void serialize (const char *filename)
Method to store the content of the grid in a file.
Static Public Member Functions
static TsdSpace * load (const char *filename)
Method to load values out of a file into the grid.
Detailed Description
Space representing a true signed distance function.
Author
Philipp Koch, Stefan May
Constructor & Destructor Documentation
obvious::TsdSpace::TsdSpace (const double voxelSize, const EnumTsdSpaceLayout layoutPartition, const EnumTsdSpaceLayout layoutSpace)
Standard constructor.
Parameters
[in] voxelSize edge length of voxels in meters
[in] layoutPartition Partition layout, i.e., voxels in partition
[in] layoutSpace Space layout, i.e., partitions in space
Member Function Documentation
unsigned int obvious::TsdSpace::getPartitionSize ()
Get number of cells along edge.
Returns
number of cells
Referenced by getVoxelSize().
obfloat obvious::TsdSpace::getMinX () const inline
Get minimum for x-coordinate.
Returns
x-coordinate
obfloat obvious::TsdSpace::getMaxX () const inline
Get maximum for x-coordinate.
Returns
x-coordinate
obfloat obvious::TsdSpace::getMinY () const inline
Get minimum for y-coordinate.
Returns
y-coordinate
obfloat obvious::TsdSpace::getMaxY () const inline
Get maximum for y-coordinate.
Returns
y-coordinate
obfloat obvious::TsdSpace::getMinZ () const inline
Get minimum for z-coordinate.
Returns
z-coordinate
obfloat obvious::TsdSpace::getMaxZ () const inline
Get maximum for z-coordinate.
Returns
z-coordinate
References getCentroid(), and setMaxTruncation().
void obvious::TsdSpace::getCentroid (obfloat centroid[3])
Get centroid of space.
Parameters
[out] centroid centroid coordinates
Referenced by getMaxZ().
void obvious::TsdSpace::setMaxTruncation (const obfloat val)
Set maximum truncation radius Function to set the max truncation.
Parameters
val new truncation radius
Referenced by getMaxZ().
double obvious::TsdSpace::getMaxTruncation () const inline
Get maximum truncation radius.
Returns
truncation radius
TsdSpacePartition**** obvious::TsdSpace::getPartitions () const inline
Get pointer to internal partition space.
Returns
pointer to 3D partition space
References interpolateNormal(), interpolateTrilinear(), interpolateTrilinearRGB(), isInsideSpace(), isPartitionInitialized(), load(), push(), pushTree(), and serialize().
bool obvious::TsdSpace::isPartitionInitialized (obfloat coord[3])
Check, if partition belonging to coordinate is initialized.
Parameters
coord query coordinate
Returns
initialization state
Referenced by getPartitions().
bool obvious::TsdSpace::isInsideSpace (Sensor * sensor)
Determine whether sensor is inside space.
Parameters
sensor
Referenced by getPartitions().
void obvious::TsdSpace::push (Sensor * sensor)
Push sensor data to space.
Parameters
[in] sensor abstract sensor instance holding current data
Referenced by getPartitions().
void obvious::TsdSpace::pushTree (Sensor * sensor)
Push sensor data to space using octree insertion.
Parameters
[in] sensor abstract sensor instance holding current data
Referenced by getPartitions().
EnumTsdSpaceInterpolate obvious::TsdSpace::interpolateTrilinear (obfloat coord[3], obfloat * tsd)
interpolate_trilineary Method to interpolate TSDF trilineary
Parameters
coord pointer to coordinates of intersection
[out] tsd interpolated TSD value
Referenced by getPartitions().
EnumTsdSpaceInterpolate obvious::TsdSpace::interpolateTrilinearRGB (obfloat coord[3], unsigned char rgb[3])
interpolate_trilineary Method to interpolate RGB data trilineary
Parameters
coord pointer to coordinates of intersection
[out] rgb interpolated RGB vector
Referenced by getPartitions().
bool obvious::TsdSpace::interpolateNormal (const obfloat * coord, obfloat * normal)
Calculates normal of crossed surface.
Parameters
normal Variable to store the components in. Has to be allocated by calling function (3 coordinates)
Referenced by getPartitions().
void obvious::TsdSpace::serialize (const char * filename)
Method to store the content of the grid in a file.
Parameters
filename
Referenced by getPartitions().
static TsdSpace* obvious::TsdSpace::load (const char * filename) static
Method to load values out of a file into the grid.
Parameters
filename
Referenced by getPartitions().
The documentation for this class was generated from the following file:
TsdSpace.h