SIFT: obvious::BoundingBoxFilter Class Reference
obvious::BoundingBoxFilter Class Reference
Data Structures
struct Dimension
Public Member Functions
BoundingBoxFilter (void)
Standard constructor with initialization.
~BoundingBoxFilter ()
Standard destructor.
FILRETVAL applyFilter (void)
Function to start filtering.
void setCentroid (const Point3D &center)
Function to get set centroid.
void setDimension (double x, double y, double z)
Function to set up dimension of bounding box around centroid.
void setDimension (double val)
Function to set up dimension of dice for filtering.
Public Member Functions inherited from obvious::FilterDistance
FilterDistance ()
Standard constructor with initialization.
virtual ~FilterDistance ()
virtual destructor
const Point3D & getCentroid (void)
Function to get set centroid.
Public Member Functions inherited from obvious::Filter
Filter ()
Standard constuctor with default parameters.
virtual ~Filter ()
Default destructor.
FILRETVAL setInput (double *addr, const unsigned int inputSize)
Function to set input of filter.
void setThreshold (const double &val)
Function to set threshold.
void setOutput (double *addr)
Function to get output of filter.
void setFilterDirection (Direction direction)
Function to change direction of filter.
unsigned int getValidSize (void) const
Function to return valid size.
double * getOutput (void) const
Function to get output address of filter.
Additional Inherited Members
Public Types inherited from obvious::IFilter
Protected Member Functions inherited from obvious::FilterDistance
virtual void setCentroidDefault (const Point3D &center)
Default function for derived classes to call.
Protected Attributes inherited from obvious::FilterDistance
Point3D _centroid
centroid to filter
Protected Attributes inherited from obvious::Filter
Direction _direction
BIGGER (default) Lowpass, SMALLER for Highpass.
double * _input
adress of the input buffer
double * _output
adress of the output buffer
double _threshold
threshold for filtering
unsigned int _size
size of both buffers
unsigned int _validSize
number of valid points in data
Member Function Documentation
FILRETVAL obvious::BoundingBoxFilter::applyFilter (void) virtual
Function to start filtering.
Note
This function must be called after setting input and output of base class.
Implements obvious::IFilter.
Referenced by BoundingBoxFilter().
void obvious::BoundingBoxFilter::setCentroid (const Point3D & center) virtual
Function to get set centroid.
Returns
_centroid
Implements obvious::FilterDistance.
Referenced by BoundingBoxFilter().
void obvious::BoundingBoxFilter::setDimension (double x, double y, double z)
Function to set up dimension of bounding box around centroid.
Parameters
x x value
y y value
z z value
Referenced by BoundingBoxFilter().
void obvious::BoundingBoxFilter::setDimension (double val)
Function to set up dimension of dice for filtering.
Parameters
x edge length of dice
The documentation for this class was generated from the following file:
BoundingBoxFilter.h