SIFT: obvious::Timer Class Reference
obvious::Timer Class Reference
This utility provides functions for precise timing measurements.
#include <Timer.h>
Public Member Functions
Timer (void)
Default constructor.
void start (void)
Starts the internal timer.
double reset (void)
Function resets the timer and returns the elapsed time.
double elapsed (void) const
Return the elapsed time since the last reset.
Detailed Description
This utility provides functions for precise timing measurements.
Author
Christian Merkl, Stefan May, Christopher Loerken and Dirk Holz
Constructor & Destructor Documentation
obvious::Timer::Timer (void) inline
Default constructor.
Timer doesn't start to run.
References elapsed(), reset(), and start().
Member Function Documentation
double obvious::Timer::reset (void)
Function resets the timer and returns the elapsed time.
Returns
elapsed time in [s] since construction of timer or last reset call
Referenced by Timer().
double obvious::Timer::elapsed (void) const
Return the elapsed time since the last reset.
Returns
elapsed time in sec since the last reset.
Referenced by Timer().
The documentation for this class was generated from the following file:
Timer.h