SIFT: obvious::Point3D Class Reference
obvious::Point3D Class Reference
points in R3 euclidian space
Public Member Functions
Point3D (const double x=0.0, const double y=0.0, const double z=0.0)
Default constructor.
Point3D (const Point3D &p)
Copy constructor.
~Point3D (void)
Standard destructor.
const double & x (void) const
Function to return x value.
const double & y (void) const
Function to return y value.
const double & z (void) const
Function to return z value.
void setX (const double &x)
Function to set x value.
void setY (const double &y)
Function to set y value.
void setZ (const double &z)
Function to set z value.
Point3D & operator= (const Point3D &right)
Overloaded allocation operator=.
double & operator[] (int idx)
Index operator [] to return ref on member for read and write access.
bool operator== (const Point3D &right) const
Overloaded comparison operator for class Point3D.
bool operator!= (const Point3D &right) const
Overloaded comparison operator for class Point3D.
bool operator< (const Point3D &right) const
Overloaded comparison operator LESS for class Point3D.
bool operator> (const Point3D &right) const
Overloaded comparison operator BIGGER for class Point3D.
Protected Attributes
double _x
x element of point
double _y
y element of point
double _z
z element of point
Friends
std::ostream & operator<< (std::ostream &ostr, Point3D &p)
Ostream operator of class point.
Detailed Description
points in R3 euclidian space
Constructor & Destructor Documentation
obvious::Point3D::Point3D (const double x = 0.0, const double y = 0.0, const double z = 0.0) inline
Default constructor.
Parameters
[in] x x value
[in] y y value
[in] z z value
obvious::Point3D::Point3D (const Point3D & p) inline
Copy constructor.
Parameters
p object of Point3D
Member Function Documentation
const double& obvious::Point3D::x (void) const inline
Function to return x value.
Returns
x value
References _x.
Referenced by setX().
const double& obvious::Point3D::y (void) const inline
Function to return y value.
Returns
y value
References _y.
Referenced by setY().
const double& obvious::Point3D::z (void) const inline
Function to return z value.
Returns
z value
References _z.
Referenced by setZ().
void obvious::Point3D::setX (const double & x) inline
Function to set x value.
Parameters
[in] x x value
References _x, and x().
void obvious::Point3D::setY (const double & y) inline
Function to set y value.
Parameters
[in] y y value
References _y, and y().
void obvious::Point3D::setZ (const double & z) inline
Function to set z value.
Parameters
[in] z z value
References _z, and z().
Point3D& obvious::Point3D::operator= (const Point3D & right) inline
Overloaded allocation operator=.
Parameters
right object of Point3D
Returns
object of Point3D
References _x, _y, and _z.
double& obvious::Point3D::operator[] (int idx) inline
Index operator [] to return ref on member for read and write access.
Parameters
[in] index index of member
See also
Axis
References _x, _y, _z, obvious::X, obvious::Y, and obvious::Z.
bool obvious::Point3D::operator== (const Point3D & right) const inline
Overloaded comparison operator for class Point3D.
Parameters
right Object of Point3D
Returns
TRUE if both objects have the same values
References _x, _y, and _z.
Referenced by operator!=().
bool obvious::Point3D::operator!= (const Point3D & right) const inline
Overloaded comparison operator for class Point3D.
Parameters
[in] right Object of Point
Returns
TRUE if objects are different
References operator==().
bool obvious::Point3D::operator< (const Point3D & right) const inline
Overloaded comparison operator LESS for class Point3D.
Parameters
[in] right Object of Point
Returns
TRUE if x value is smaller
References _x, _y, and _z.
bool obvious::Point3D::operator> (const Point3D & right) const inline
Overloaded comparison operator BIGGER for class Point3D.
Parameters
[in] right Object of Point
Returns
TRUE if objects are different
References _x, _y, and _z.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & ostr, Point3D & p) friend
Ostream operator of class point.
Parameters
ostr ostream object
[in] p Point3D object
Returns
ostream object
The documentation for this class was generated from the following file:
Point3D.h