SIFT: obvious::Time Class Reference
obvious::Time Class Reference
A simple class to get the current time in sec and usec from the date 1970.
#include <Time.h>
Public Member Functions
Time (void)
Default constructor.
Time (const Time &time)
Copy constructor.
double hours (void) const
Gets the hours of this day.
double min (void) const
Gets the time in minutes of this day.
double sec (void) const
Gets the time in seconds of this day.
double mus (void) const
Gets the time in museconds of this day.
Time & operator= (const Time &time)
Assignment operator.
double operator- (const Time &time) const
Calculates the time difference between this and time object.
Time & operator+= (const double sec)
Adds the given sec to this object.
Static Public Member Functions
static Time now (void)
Gets the current time.
Detailed Description
A simple class to get the current time in sec and usec from the date 1970.
You can easly calculate a duration time with the operator-.
Author
Christian Merkl
Constructor & Destructor Documentation
obvious::Time::Time (void)
Default constructor.
Sets all members to 0.
obvious::Time::Time (const Time & time) inline
Copy constructor.
Parameters
time will be copied.
References hours(), min(), mus(), now(), operator+=(), operator-(), operator=(), and sec().
Member Function Documentation
double obvious::Time::hours (void) const
Gets the hours of this day.
Returns
hours of this day.
Referenced by Time().
double obvious::Time::min (void) const
Gets the time in minutes of this day.
Returns
minutes of this day.
Referenced by Time().
double obvious::Time::sec (void) const
Gets the time in seconds of this day.
Returns
seconds of this day.
Referenced by Time().
double obvious::Time::mus (void) const
Gets the time in museconds of this day.
Returns
mus of this day.
Referenced by Time().
static Time obvious::Time::now (void) static
Gets the current time.
Returns
the current time as Time object.
Referenced by Time().
Time& obvious::Time::operator= (const Time & time)
Assignment operator.
Parameters
time will be copied.
Referenced by Time().
double obvious::Time::operator- (const Time & time) const
Calculates the time difference between this and time object.
Parameters
time will be subtracted from this.
Referenced by Time().
Time& obvious::Time::operator+= (const double sec)
Adds the given sec to this object.
Parameters
sec will be added to this object.
Referenced by Time().
The documentation for this class was generated from the following file:
Time.h