SIFT: obvious::Quaternion Class Reference
obvious::Quaternion Class Reference
#include <Quaternion.h>
Public Member Functions
Quaternion ()
Default constructor, Rotation about 0 degrees.
Quaternion (obfloat w, obfloat x, obfloat y, obfloat z)
Constructor.
Quaternion (Matrix R)
Constructor.
virtual ~Quaternion ()
Destructor.
double w () const
Const accessor.
double x () const
Const accessor.
double y () const
Const accessor.
double z () const
Const accessor.
Quaternion & operator+= (const Quaternion &q)
Add quaternion.
Quaternion & operator-= (const Quaternion &q)
Subtract quaternion.
void conjugate ()
Conjugate quaternion.
Matrix convertToMatrix ()
Convert quaterion to 3x3 rotation matrix.
Static Public Member Functions
static Quaternion QuaternionAroundX (obfloat psi)
Create quaternion rotation about the x-axis.
static Quaternion QuaternionAroundY (obfloat theta)
Create quaternion rotation about the y-axis.
static Quaternion QuaternionAroundZ (obfloat phi)
Create quaternion rotation about the z-axis.
Friends
Quaternion operator+ (const Quaternion &q1, const Quaternion &q2)
Add two quaternions.
Quaternion operator* (const Quaternion &q1, const Quaternion &q2)
Multiply two quaternions.
Detailed Description
Author
Stefan May
Date
05.12. 2014
Constructor & Destructor Documentation
obvious::Quaternion::Quaternion (obfloat w, obfloat x, obfloat y, obfloat z) inline
Constructor.
Parameters
w q.w
x q.x
y q.y
z q.z
References w(), x(), y(), and z().
obvious::Quaternion::Quaternion (Matrix R)
Constructor.
Parameters
R 2x2 or 3x3 rotation matrix, for 2x2 a rotation about the z-axis is created
Member Function Documentation
static Quaternion obvious::Quaternion::QuaternionAroundX (obfloat psi) static
Create quaternion rotation about the x-axis.
Parameters
psi rotation angle
Returns
Quaternion instance
static Quaternion obvious::Quaternion::QuaternionAroundY (obfloat theta) static
Create quaternion rotation about the y-axis.
Parameters
theta rotation angle
Returns
Quaternion instance
static Quaternion obvious::Quaternion::QuaternionAroundZ (obfloat phi) static
Create quaternion rotation about the z-axis.
Parameters
phi rotation angle
Returns
Quaternion instance
double obvious::Quaternion::w () const inline
Const accessor.
Returns
w-component
Referenced by Quaternion().
double obvious::Quaternion::x () const inline
Const accessor.
Returns
x-component of axis
Referenced by Quaternion().
double obvious::Quaternion::y () const inline
Const accessor.
Returns
y-component of axis
Referenced by Quaternion().
double obvious::Quaternion::z () const inline
Const accessor.
Returns
z-component of axis
References operator*, and operator+.
Referenced by Quaternion().
Quaternion& obvious::Quaternion::operator+= (const Quaternion & q) inline
Add quaternion.
Parameters
q quaternion
Returns
resulting quaternion, i.e., this instance
Quaternion& obvious::Quaternion::operator-= (const Quaternion & q) inline
Subtract quaternion.
Parameters
q quaternion
Returns
resulting quaternion, i.e., this instance
Matrix obvious::Quaternion::convertToMatrix ()
Convert quaterion to 3x3 rotation matrix.
Returns
matrix
Referenced by conjugate().
Friends And Related Function Documentation
Quaternion operator+ (const Quaternion & q1, const Quaternion & q2) friend
Add two quaternions.
Parameters
q1 first quaternion
q2 second quaternion
Returns
resulting quaternion
Referenced by z().
Quaternion operator* (const Quaternion & q1, const Quaternion & q2) friend
Multiply two quaternions.
Parameters
q1 first quaternion
q2 second quaternion
Returns
resulting quaternion
Referenced by z().
The documentation for this class was generated from the following file:
Quaternion.h