SIFT: obvious::IRigidEstimator Class Reference
obvious::IRigidEstimator Class Reference abstract
An estimator for registering points clouds into one common coordinate system.
#include <IRigidEstimator.h>
Public Member Functions
IRigidEstimator ()
Default constructor.
virtual ~IRigidEstimator ()
Destructor.
virtual void setModel (double **model, unsigned int size, double **normals=NULL)=0
Setting internal pointer to model array.
virtual void setScene (double **scene, unsigned int size, double **normals=NULL)=0
Setting internal pointer to scene array.
virtual void setPairs (std::vector< StrCartesianIndexPair > *vPairs)=0
Setting assigned point pairs.
virtual double getRMS ()=0
Access the RMS error that has been calculated by the setPairs method.
virtual void estimateTransformation (Matrix *T)=0
Determine the transformation matrix that registers the scene to the model.
Detailed Description
An estimator for registering points clouds into one common coordinate system.
Author
Stefan May
Member Function Documentation
virtual void obvious::IRigidEstimator::setModel (double ** model, unsigned int size, double ** normals = NULL) pure virtual
Setting internal pointer to model array.
The model is seen as the ground truth against which the scene has to be registered.
Parameters
model Pointer to 3 dimensional model array
Implemented in obvious::ClosedFormEstimator2D, obvious::PointToPlaneEstimator3D, obvious::PointToPointEstimator3D, and obvious::PointToLine2DEstimator.
Referenced by ~IRigidEstimator().
virtual void obvious::IRigidEstimator::setScene (double ** scene, unsigned int size, double ** normals = NULL) pure virtual
Setting internal pointer to scene array.
(See commend for setModel)
Parameters
scene Pointer to 3 dimensional scene array
Implemented in obvious::ClosedFormEstimator2D, obvious::PointToPlaneEstimator3D, obvious::PointToPointEstimator3D, and obvious::PointToLine2DEstimator.
Referenced by ~IRigidEstimator().
virtual void obvious::IRigidEstimator::setPairs (std::vector< StrCartesianIndexPair > * vPairs) pure virtual
Setting assigned point pairs.
You can use a pair assigner for this purpose. The deviation, i.e. the mean distance, between those pairs is also determined within this method.
Parameters
vPairs Vector of pairs of indices. Each index pair references a scene and a model point.
Implemented in obvious::ClosedFormEstimator2D, obvious::PointToPlaneEstimator3D, obvious::PointToPointEstimator3D, and obvious::PointToLine2DEstimator.
Referenced by ~IRigidEstimator().
virtual double obvious::IRigidEstimator::getRMS () pure virtual
Access the RMS error that has been calculated by the setPairs method.
Returns
RMS error
Implemented in obvious::ClosedFormEstimator2D, obvious::PointToPlaneEstimator3D, obvious::PointToPointEstimator3D, and obvious::PointToLine2DEstimator.
Referenced by ~IRigidEstimator().
virtual void obvious::IRigidEstimator::estimateTransformation (Matrix * T) pure virtual
Determine the transformation matrix that registers the scene to the model.
Parameters
transformation matrix as return parameter
Implemented in obvious::PointToPlaneEstimator3D, obvious::PointToPointEstimator3D, obvious::ClosedFormEstimator2D, and obvious::PointToLine2DEstimator.
Referenced by ~IRigidEstimator().
The documentation for this class was generated from the following file:
IRigidEstimator.h